// Hidden-burn demo: burn a shielded token WITHOUT the contract, so the burnt
// amount stays hidden from the indexer.
//
//   1. bring up a local Midnight v8 stack (testkit reads ./compose.yml)
//   2. build a wallet from a prefunded genesis seed
//   3. deploy a ShieldedFungibleToken + mint to self  (via the vendored contract)
//   4. BURN by a direct wallet -> burn-address Zswap transfer (NO contract call)
//   5. decode the burn tx and write the "what the indexer sees" report
//
// Contrast with `reproduce.ts`: there the burn goes through the contract's
// `burn` circuit, which `disclose()`s the coin value + change into the public
// VM transcript, so the amount leaks. Here the burn is a plain shielded
// transfer to the zero (burn) coin public key: the value lives only inside a
// Pedersen commitment, so the indexer never sees it. The trade-off is the
// contract cannot see or count this burn.
//
// Run from the package root:  npx tsx src/hidden-burn.ts
// Override defaults via env: TOKEN_NAME, TOKEN_SYMBOL, MINT_AMOUNT, BURN_AMOUNT.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { unshieldedToken } from "@midnight-ntwrk/ledger-v8";
import { setNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import { ttlOneHour } from "@midnight-ntwrk/midnight-js-utils";
import { getTestEnvironment, LocalTestConfiguration } from "@midnight-ntwrk/testkit-js";
import { ShieldedAddress, ShieldedCoinPublicKey } from "@midnight-ntwrk/wallet-sdk";
import { pino } from "pino";
import * as Rx from "rxjs";
import { WebSocket } from "ws";
import { ShieldedFungibleToken } from "./contract.js";
import { decodeTx, formatDecode } from "./decode.js";
import { configureProviders } from "./providers.js";
import { MidnightWalletProvider } from "./wallet-provider.js";
import { waitForShieldedToken, waitForUnshieldedFunds } from "./wallet-utils.js";

// Apollo (indexer subscriptions) needs a global WebSocket.
(globalThis as { WebSocket?: unknown }).WebSocket = WebSocket;

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const ZK_CONFIG_PATH = resolve(PKG_ROOT, "artifacts", "shielded-token", "ShieldedFungibleToken");
const OUT_DIR = resolve(PKG_ROOT, "out");

const GENESIS_SEED = "0000000000000000000000000000000000000000000000000000000000000001";
const TOKEN_NAME = process.env.TOKEN_NAME ?? "OZ Test Token";
const TOKEN_SYMBOL = process.env.TOKEN_SYMBOL ?? "OZT";
const MINT_AMOUNT = BigInt(process.env.MINT_AMOUNT ?? "1000000");
const BURN_AMOUNT = BigInt(process.env.BURN_AMOUNT ?? "400000");

// The shielded burn address: the all-zero coin public key (32 zero bytes).
// Whoever would spend a coin needs the secret for its coin public key; nobody
// holds the secret for the zero key, so the coin is destroyed. This is exactly
// what the contract's `shieldedBurnAddress()` resolves to.
const BURN_COIN_PUBLIC_KEY_HEX = "00".repeat(32);

const logger = pino({
	level: process.env.DEBUG_LEVEL ?? "info",
	transport: { target: "pino-pretty", options: { colorize: true, translateTime: "HH:MM:ss" } },
});

const hexOf = (u8: Uint8Array): string => Buffer.from(u8).toString("hex");

function writeReport(args: {
	tokenName: string;
	tokenSymbol: string;
	contractAddress: string;
	tokenColor: string;
	mintAmount: string;
	burnAmount: string;
	burnHex: string;
}): string {
	const d = decodeTx(args.burnHex);
	const allActions = d.intents.flatMap((i) => i.actions);
	const contractCalls = allActions.filter((a) => a.kind === "ContractCall");
	const off = d.guaranteedOffer ?? { inputs: [], outputs: [], transients: 0, deltas: [] };

	const lines: string[] = [];
	lines.push("# Hidden burn — what a public indexer sees (auto-generated)");
	lines.push("");
	lines.push("Generated by `npx tsx src/hidden-burn.ts`. The token is minted through");
	lines.push("the contract, but **burned by a direct wallet → burn-address Zswap**");
	lines.push("**transfer that never touches the contract**. The burn tx below is decoded");
	lines.push("from its raw on-wire bytes, so everything shown is what the indexer reads.");
	lines.push("");
	lines.push("## Run parameters");
	lines.push("");
	lines.push("```");
	lines.push(`Token            : ${args.tokenName} (${args.tokenSymbol})`);
	lines.push(`Contract address : ${args.contractAddress}`);
	lines.push(`Token color      : ${args.tokenColor}`);
	lines.push(`Minted           : ${args.mintAmount}  (through the contract)`);
	lines.push(`Burned           : ${args.burnAmount}  (direct wallet transfer to the zero coin key)`);
	lines.push("```");
	lines.push("");
	lines.push("## The burn transaction (decoded)");
	lines.push("");
	lines.push("```");
	lines.push(`transactionHash : ${d.transactionHash}`);
	lines.push(`byteLength      : ${d.byteLength}`);
	lines.push(`ContractCall actions : ${contractCalls.length}   <-- none: the contract is not involved`);
	lines.push(`Zswap offer     : inputs=${off.inputs.length} outputs=${off.outputs.length} transients=${off.transients}`);
	off.deltas.forEach((x) => lines.push(`  delta ${x.type} = ${x.delta}`));
	off.inputs.forEach((i, n) => lines.push(`  input[${n}]  nullifier  = ${i.nullifier}`));
	off.outputs.forEach((o, n) => lines.push(`  output[${n}] commitment = ${o.commitment}`));
	lines.push("```");
	lines.push("");
	lines.push("Public: a shielded transfer. The indexer sees one spent-coin nullifier and");
	lines.push("the new output commitments (the burn output + change). There is **no contract**");
	lines.push("**call and no VM transcript carrying the value** — the burnt amount lives only");
	lines.push(`inside a Pedersen commitment. The token amount (${args.burnAmount}) is **not** derivable.`);
	lines.push("");
	lines.push("## Contract burn vs. direct burn");
	lines.push("");
	lines.push("| | Contract `burn` (reproduce.ts) | Direct wallet burn (this script) |");
	lines.push("|---|---|---|");
	lines.push("| Path | calls the `burn` circuit | plain Zswap transfer to zero coin key |");
	lines.push("| Amount in transcript | **yes** — `disclose`d coin value + change | n/a — no contract transcript |");
	lines.push("| Amount visible to indexer | **yes**, derivable | **no**, only a Pedersen commitment |");
	lines.push("| Contract can count it (`totalBurned`) | yes | **no** — invisible to the contract |");
	lines.push("| Owner / recipient | hidden | hidden |");
	lines.push("");
	lines.push("So hiding the burnt amount IS possible, but only by leaving the contract out");
	lines.push("of the burn. A contract-mediated burn must `disclose` the coin to spend it.");
	lines.push("");

	const reportPath = resolve(OUT_DIR, "HIDDEN-BURN-VIEW.md");
	writeFileSync(reportPath, lines.join("\n"));
	writeFileSync(resolve(OUT_DIR, "3-direct-burn.hex"), args.burnHex);
	writeFileSync(resolve(OUT_DIR, "3-direct-burn.decode.txt"), formatDecode(d));
	return reportPath;
}

async function main(): Promise<void> {
	mkdirSync(OUT_DIR, { recursive: true });
	logger.info(`zkConfigPath: ${ZK_CONFIG_PATH}`);

	// If HB_*_PORT are set, an externally-managed stack is already up (see
	// scripts/run-hidden-burn.sh). We skip testkit's container management — its
	// testcontainers log-wait is flaky in some environments — and point straight
	// at the published ports. Otherwise fall back to testkit's LocalTestEnvironment.
	const injected =
		process.env.HB_INDEXER_PORT && process.env.HB_NODE_PORT && process.env.HB_PS_PORT;
	const testEnv = injected ? undefined : getTestEnvironment(logger);
	const providersToStop: MidnightWalletProvider[] = [];
	try {
		let envConfig: unknown;
		if (injected) {
			// testkit's getTestEnvironment() normally does this; we bypassed it.
			setNetworkId("undeployed");
			envConfig = new LocalTestConfiguration({
				indexer: Number(process.env.HB_INDEXER_PORT),
				node: Number(process.env.HB_NODE_PORT),
				proofServer: Number(process.env.HB_PS_PORT),
			} as never);
			logger.info(`Using injected stack: ${JSON.stringify(envConfig)}`);
		} else {
			logger.info("Starting local test environment (node + indexer + proof-server)...");
			envConfig = await testEnv!.start();
			logger.info(`Environment up: ${JSON.stringify(envConfig)}`);
		}

		const walletProvider = await MidnightWalletProvider.build(
			logger,
			envConfig as never,
			GENESIS_SEED,
		);
		providersToStop.push(walletProvider);
		await walletProvider.start();

		await waitForUnshieldedFunds(logger, walletProvider.wallet, unshieldedToken());

		const providers = configureProviders(walletProvider, ZK_CONFIG_PATH);

		// 1) deploy + 2) mint to self  (through the vendored contract)
		const token = await ShieldedFungibleToken.deploy(
			providers,
			TOKEN_NAME,
			TOKEN_SYMBOL,
			ZK_CONFIG_PATH,
			logger,
		);
		const minted = await token.mint(walletProvider.getCoinPublicKey(), MINT_AMOUNT);
		const colorHex = hexOf(minted.color);

		// 3) wait for the coin to sync, then BURN it via a direct wallet transfer
		//    to the zero (burn) coin public key — bypassing the contract entirely.
		await waitForShieldedToken(logger, walletProvider.wallet, colorHex, minted.value);

		const shieldedState = await Rx.firstValueFrom(walletProvider.wallet.shielded.state);
		const myAddr = shieldedState.address;
		// Burn address: zero coin public key. The encryption key only governs who
		// can *detect/decrypt* the output ciphertext, not who can spend it; we reuse
		// the sender's (a valid curve point) so the transfer is well-formed. The
		// coin is still unspendable by anyone because its coin public key is zero.
		const burnAddress = new ShieldedAddress(
			ShieldedCoinPublicKey.fromHexString(BURN_COIN_PUBLIC_KEY_HEX),
			myAddr.encryptionPublicKey,
		);
		logger.info(`Burn address coin key: ${burnAddress.coinPublicKeyString()}`);
		logger.info(`Burning ${BURN_AMOUNT} of ${colorHex} by direct transfer to the burn address...`);

		const recipe = await walletProvider.wallet.transferTransaction(
			[
				{
					type: "shielded",
					outputs: [
						{ type: colorHex as never, receiverAddress: burnAddress, amount: BURN_AMOUNT },
					],
				},
			],
			{
				shieldedSecretKeys: walletProvider.zswapSecretKeys,
				dustSecretKey: walletProvider.dustSecretKey,
			},
			{ ttl: ttlOneHour(), payFees: true },
		);
		const finalized = await walletProvider.wallet.finalizeRecipe(recipe as never);
		const burnHex = Buffer.from(finalized.serialize()).toString("hex");
		logger.info(`Built direct-burn tx: ${burnHex.length / 2} bytes`);

		const txId = await walletProvider.wallet.submitTransaction(finalized);
		logger.info(`Submitted direct-burn tx, wallet returned id: ${txId}`);

		const reportPath = writeReport({
			tokenName: TOKEN_NAME,
			tokenSymbol: TOKEN_SYMBOL,
			contractAddress: token.addressHex,
			tokenColor: colorHex,
			mintAmount: MINT_AMOUNT.toString(),
			burnAmount: BURN_AMOUNT.toString(),
			burnHex,
		});

		logger.info("==================================================================");
		logger.info("DONE (hidden burn). Summary:");
		logger.info(`  contract : ${token.addressHex}`);
		logger.info(`  minted ${MINT_AMOUNT} (contract), burned ${BURN_AMOUNT} (direct transfer)`);
		logger.info(`  report : ${reportPath}`);
		logger.info(`  raw hex + decode in: ${OUT_DIR} (3-direct-burn.*)`);
		logger.info("==================================================================");
	} catch (e) {
		logger.error(`Hidden-burn demo failed: ${e instanceof Error ? e.message : String(e)}`);
		if (e instanceof Error && e.stack) logger.error(e.stack);
		throw e;
	} finally {
		for (const p of providersToStop) {
			try {
				await p.stop();
			} catch (e) {
				logger.warn(`stop wallet: ${e instanceof Error ? e.message : String(e)}`);
			}
		}
		try {
			if (testEnv) await testEnv.shutdown();
		} catch (e) {
			logger.warn(`shutdown: ${e instanceof Error ? e.message : String(e)}`);
		}
	}
}

main().then(
	() => process.exit(0),
	() => process.exit(1),
);
