// End-to-end, non-interactive reproduction:
//   1. bring up a local Midnight v8 stack (testkit reads ./compose.yml)
//   2. build a wallet from a prefunded genesis seed
//   3. deploy a ShieldedFungibleToken
//   4. mint to self
//   5. burn part of it (sends to the burn address, returns change)
//   6. decode every submitted tx and write the "what the indexer sees" report
//
// Run from the package root:  npm run reproduce   (i.e. tsx src/reproduce.ts)
// Override defaults via env: TOKEN_NAME, TOKEN_SYMBOL, MINT_AMOUNT, BURN_AMOUNT,
// DEBUG_LEVEL.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { unshieldedToken } from "@midnight-ntwrk/ledger-v8";
import { getTestEnvironment } from "@midnight-ntwrk/testkit-js";
import { pino } from "pino";
import { WebSocket } from "ws";
import { ShieldedFungibleToken } from "./contract.js";
import { type DecodedTx, decodeTx, formatDecode } from "./decode.js";
import { configureProviders } from "./providers.js";
import { MidnightWalletProvider } from "./wallet-provider.js";
import { waitForShieldedToken, waitForUnshieldedFunds } from "./wallet-utils.js";

// Apollo (indexer subscriptions) needs a global WebSocket.
(globalThis as { WebSocket?: unknown }).WebSocket = WebSocket;

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const ZK_CONFIG_PATH = resolve(PKG_ROOT, "artifacts", "shielded-token", "ShieldedFungibleToken");
const OUT_DIR = resolve(PKG_ROOT, "out");

// Prefunded genesis account on the dev preset (seeds ...0001-0004 all work).
const GENESIS_SEED = "0000000000000000000000000000000000000000000000000000000000000001";
const TOKEN_NAME = process.env.TOKEN_NAME ?? "OZ Test Token";
const TOKEN_SYMBOL = process.env.TOKEN_SYMBOL ?? "OZT";
const MINT_AMOUNT = BigInt(process.env.MINT_AMOUNT ?? "1000000");
const BURN_AMOUNT = BigInt(process.env.BURN_AMOUNT ?? "400000");

const logger = pino({
	level: process.env.DEBUG_LEVEL ?? "info",
	transport: { target: "pino-pretty", options: { colorize: true, translateTime: "HH:MM:ss" } },
});

const hexOf = (u8: Uint8Array): string => Buffer.from(u8).toString("hex");

interface RunSummary {
	tokenName: string;
	tokenSymbol: string;
	contractAddress: string;
	tokenColor: string;
	mintAmount: string;
	burnAmount: string;
	changeAmount: string;
}

type DecodedWithMeta = DecodedTx & { index: number; kind: string };

function publicNote(kind: string): string {
	if (kind === "deploy") return "the contract address and its initial public state. No coins move.";
	if (kind === "mint")
		return "a `mint` call, the token color, the minted amount (in `shieldedMints`), and one new coin commitment. The recipient is sealed in the commitment.";
	if (kind === "burn")
		return "a `burn` call, the spent coin's nullifier, two new commitments (burn-address coin + change), and (for this contract) the coin value and change disclosed in the transcript, so the burned amount is derivable. Owners stay hidden.";
	return "a contract transaction.";
}

/** Build the markdown "indexer view" report from the captured + decoded txs. */
function writeReport(summary: RunSummary, decoded: DecodedWithMeta[]): string {
	const lines: string[] = [];
	lines.push("# Shielded token — what a public indexer sees (auto-generated)");
	lines.push("");
	lines.push("Generated by `npm run reproduce`. Each transaction below was decoded");
	lines.push("from its **raw on-wire bytes** with `@midnight-ntwrk/ledger-v8`, so");
	lines.push("everything shown is what a public observer (the indexer) can read.");
	lines.push("");
	lines.push("## Run parameters");
	lines.push("");
	lines.push("```");
	lines.push(`Token            : ${summary.tokenName} (${summary.tokenSymbol})`);
	lines.push(`Contract address : ${summary.contractAddress}`);
	lines.push(`Token color      : ${summary.tokenColor}`);
	lines.push(`Minted           : ${summary.mintAmount}`);
	lines.push(`Burned           : ${summary.burnAmount}  (change ${summary.changeAmount})`);
	lines.push("```");
	lines.push("");

	for (const d of decoded) {
		const allActions = d.intents.flatMap((i) => i.actions);
		const call = allActions.find((a) => a.kind === "ContractCall");
		const deploy = allActions.find((a) => a.kind === "ContractDeploy");
		const off = d.guaranteedOffer ?? { inputs: [], outputs: [], transients: 0, deltas: [] };
		lines.push(`## TX #${d.index} — ${d.kind}`);
		lines.push("");
		lines.push("```");
		lines.push(`transactionHash : ${d.transactionHash}`);
		lines.push(`byteLength      : ${d.byteLength}`);
		if (deploy) lines.push(`ContractDeploy  : address=${deploy.address}`);
		if (call) {
			lines.push(`ContractCall    : address=${call.address} entryPoint=${call.entryPoint}`);
			const ef = call.guaranteedTranscript?.effects;
			if (ef) {
				lines.push(`  shieldedMints           : ${JSON.stringify(ef.shieldedMints)}`);
				lines.push(`  claimedShieldedSpends   : ${ef.claimedShieldedSpends.length}`);
				lines.push(`  claimedShieldedReceives : ${ef.claimedShieldedReceives.length}`);
				lines.push(`  claimedNullifiers       : ${ef.claimedNullifiers.length}`);
			}
		}
		lines.push(`Zswap offer     : inputs=${off.inputs.length} outputs=${off.outputs.length} transients=${off.transients}`);
		off.deltas.forEach((x) => lines.push(`  delta ${x.type} = ${x.delta}`));
		off.inputs.forEach((i, n) => lines.push(`  input[${n}]  nullifier  = ${i.nullifier}`));
		off.outputs.forEach((o, n) => lines.push(`  output[${n}] commitment = ${o.commitment}`));
		lines.push("```");
		lines.push("");
		lines.push(`Public: ${publicNote(d.kind)}`);
		lines.push("");
		lines.push(`Raw bytes: \`out/${d.index}-${d.kind}.hex\` · full decode: \`out/${d.index}-${d.kind}.decode.txt\``);
		lines.push("");
	}

	lines.push("## Public vs hidden");
	lines.push("");
	lines.push("| Always public | Always hidden |");
	lines.push("|---|---|");
	lines.push("| Contract address + entry point (`mint`/`burn`) | Coin owners / recipient public keys |");
	lines.push("| Token color (type) | Which output commitment is which recipient |");
	lines.push("| New coin commitments, spent-coin nullifiers | The value sealed inside any commitment |");
	lines.push("| Public VM transcript + gas | Dust balance (only nullifier + commitment) |");
	lines.push("| ZK proof is present | What the ZK proof proves |");
	lines.push("");
	lines.push("Amount visibility depends on the circuit. In this archived `ShieldedERC20`:");
	lines.push("`mint` puts the amount in the `shieldedMints` effect, and `burn` `disclose()`s");
	lines.push("the coin value and change into the public transcript, so **both leak the amount**.");
	lines.push("The coin owners stay hidden in both cases.");
	lines.push("");

	const reportPath = resolve(OUT_DIR, "INDEXER-VIEW.md");
	writeFileSync(reportPath, lines.join("\n"));
	return reportPath;
}

async function main(): Promise<void> {
	mkdirSync(OUT_DIR, { recursive: true });
	logger.info(`zkConfigPath: ${ZK_CONFIG_PATH}`);
	logger.info(`Output dir:  ${OUT_DIR}`);

	const testEnv = getTestEnvironment(logger);
	const providersToStop: MidnightWalletProvider[] = [];
	try {
		logger.info("Starting local test environment (node + indexer + proof-server)...");
		const envConfig = await testEnv.start();
		logger.info(`Environment up: ${JSON.stringify(envConfig)}`);

		const walletProvider = await MidnightWalletProvider.build(logger, envConfig, GENESIS_SEED);
		providersToStop.push(walletProvider);
		await walletProvider.start();

		const unshielded = await waitForUnshieldedFunds(logger, walletProvider.wallet, unshieldedToken());
		const night = unshielded.balances[unshieldedToken().raw];
		logger.info(`NIGHT balance: ${night}`);

		const providers = configureProviders(walletProvider, ZK_CONFIG_PATH);

		// 1) deploy
		const token = await ShieldedFungibleToken.deploy(providers, TOKEN_NAME, TOKEN_SYMBOL, ZK_CONFIG_PATH, logger);

		// 2) mint to self
		const minted = await token.mint(walletProvider.getCoinPublicKey(), MINT_AMOUNT);
		const colorHex = hexOf(minted.color);

		// 3) wait for the coin to sync, then burn part of it
		await waitForShieldedToken(logger, walletProvider.wallet, colorHex, minted.value);
		const burnResult = await token.burn(minted, BURN_AMOUNT);
		const changeAmount = burnResult.change.is_some ? burnResult.change.value.value : 0n;

		// 4) decode every captured tx + write artifacts and the report
		const decoded: DecodedWithMeta[] = [];
		for (const tx of walletProvider.submittedTxs) {
			const d: DecodedWithMeta = { index: tx.index, kind: tx.kind, ...decodeTx(tx.hex) };
			decoded.push(d);
			writeFileSync(resolve(OUT_DIR, `${tx.index}-${tx.kind}.hex`), tx.hex);
			writeFileSync(resolve(OUT_DIR, `${tx.index}-${tx.kind}.decode.txt`), formatDecode(d));
		}
		const reportPath = writeReport(
			{
				tokenName: TOKEN_NAME,
				tokenSymbol: TOKEN_SYMBOL,
				contractAddress: token.addressHex,
				tokenColor: colorHex,
				mintAmount: MINT_AMOUNT.toString(),
				burnAmount: BURN_AMOUNT.toString(),
				changeAmount: changeAmount.toString(),
			},
			decoded,
		);

		logger.info("==================================================================");
		logger.info("DONE. Summary:");
		logger.info(`  contract : ${token.addressHex}`);
		for (const tx of walletProvider.submittedTxs) {
			logger.info(`  tx #${tx.index} ${tx.kind.padEnd(6)} ${tx.byteLength} bytes  ${tx.transactionHash}`);
		}
		logger.info(`  minted ${MINT_AMOUNT}, burned ${BURN_AMOUNT}, change ${changeAmount}`);
		logger.info(`  report : ${reportPath}`);
		logger.info(`  raw hex + decodes in: ${OUT_DIR}`);
		logger.info("==================================================================");
	} catch (e) {
		logger.error(`Reproduction failed: ${e instanceof Error ? e.message : String(e)}`);
		if (e instanceof Error && e.stack) logger.error(e.stack);
		throw e;
	} finally {
		for (const p of providersToStop) {
			try {
				logger.info("Stopping wallet...");
				await p.stop();
			} catch (e) {
				logger.warn(`stop wallet: ${e instanceof Error ? e.message : String(e)}`);
			}
		}
		try {
			logger.info("Shutting down test environment...");
			await testEnv.shutdown();
		} catch (e) {
			logger.warn(`shutdown: ${e instanceof Error ? e.message : String(e)}`);
		}
	}
}

main().then(
	() => process.exit(0),
	() => process.exit(1),
);
